sudo: required
services:
  - docker

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec web sleep 10
  - docker-compose exec web bash -l -c "rake db:setup"
  - docker-compose exec web bash -l -c "rake db:migrate"
  - docker-compose exec web bower install --allow-root

script:
  - docker-compose exec web bash -l -c "rake test"
  - bundle exec danger
