sudo: required
services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose up -d --build
  - docker-compose exec web bash -l -c "sleep 10"
  - docker-compose exec web bash -l -c "bundle install"
  - docker-compose exec web bash -l -c "rake db:setup || rake db:migrate"

script:
  - sed -ri "s/REPO_TOKEN/$REPO_TOKEN/" .coveralls.yml
  - docker-compose exec web bash -l -c "CI=true TRAVIS=true rake test:all"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
